name: "png2font/build-ttf"
description: "Build TTF font from Png2Ttf raw directory"

inputs:
  strict:
    default: "nostrict"
    required: false
    description: "Strict or not strict"
  weight:
    default: "0"
    required: false
    description: "Font weight"
  fontname:
    default: "CI Generated Font"
    required: false
    description: "Font name"
  filename-prefix:
    default: "generated"
    required: false
    description: "Font filename prefix"
  raw-directory:
    default: "raw"
    required: false
    description: "Raw directory"
  builder-version:
    default: "master"
    required: false
    description: "Builder version"
  skip-builder-download:
    default: "false"
    required: false
    description: "Skip builder download. You must put Png2Ttf repository in __builder directory"

runs:
  using: "composite"
  steps:
    - name: Download builder
      if: ${{ inputs.skip-builder-download != 'true' }}
      uses: actions/checkout@v4
      with:
        repository: mkaraki/Png2Font
        path: __builder
        ref: ${{ inputs.builder-version }}
        fetch-depth: 0
        submodules: recursive

    - name: Install requirements
      shell: bash
      run: __builder/build/_install_reqs_ubuntu.sh

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Run build
      shell: bash
      run: |
        cd __builder/build
        dotnet run -- --rawdir "${{ github.workspace }}/__to_build/${{ inputs.raw-directory }}" --weight ${{ inputs.weight }} --${{ inputs.strict }} --filename ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }} --fontname "${{ inputs.fontname }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }}
        path: |
          __builder/build/*.ttf
          __builder/build/*.sources.tsv

    - name: Upload source bitmap
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }}-bmp
        path: |
          __builder/build/workdir/*.bmp

    - name: Upload source svg
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }}-svg
        path: |
          __builder/build/workdir/*.svg