# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: E2E actions build-ttf with master version of Png2Font

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  with-master-version-of-builder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: sakamata-ch/SakamataFontProject

    - uses: actions/checkout@v4
      with:
        path: png2ttf

    - name: Build
      uses: ./png2ttf/__builder/builder-ghaction
      with:
        raw-directory: raw
        filename-prefix: artifact-font-nf
        fontname: artifact
        builder-version: master
    
    - name: Download generated font
      uses: actions/download-artifact@v4
      with:
        name: artifact-font-nf-0-nostrict
        path: artifact-font-nf

    - name: Check generated font
      run: |
        export GEN_FONT_FILEINFO=`ls -lh artifact-font-nf/artifact-font-nf-0-nostrict.ttf`
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$GEN_FONT_FILEINFO" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
