name: chart-generator E2E Test

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'chart-generator'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: sakamata-ch/SakamataFontProject
        path: 'testfixtures/fontdir'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test chart generation
      run: dotnet run -- --rawdir=../testfixtures/fontdir/raw

    - name: Check generated char.tsv
      run: |
        export CHAR_TSV_LINES=`wc -l output/char.tsv`
        export CHAR_TSV_HEAD=`head output/char.tsv`
        echo "`output/char.tsv` returns $CHAR_TSV_LINES lines." >> $GITHUB_STEP_SUMMARY
        echo "Head 10 lines:" >> $GITHUB_STEP_SUMMARY
        echo '' >> $GITHUB_STEP_SUMMARY
        echo '```tsv' >> $GITHUB_STEP_SUMMARY
        echo "$CHAR_TSV_HEAD" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo '' >> $GITHUB_STEP_SUMMARY

    - name: Check generated file.tsv
      run: |
        export FILE_TSV_LINES=`wc -l output/file.tsv`
        export FILE_TSV_HEAD=`head output/file.tsv`
        echo "`output/file.tsv` returns $FILE_TSV_LINES lines." >> $GITHUB_STEP_SUMMARY
        echo "Head 10 lines:\n\n\`\`\`tsv\n$FILE_TSV_HEAD\n\`\`\`\n\n" >> $GITHUB_STEP_SUMMARY
        echo '' >> $GITHUB_STEP_SUMMARY
        echo '```tsv' >> $GITHUB_STEP_SUMMARY
        echo "$FILE_TSV_HEAD" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo '' >> $GITHUB_STEP_SUMMARY
